# -*- coding: utf-8 -*-
"""bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1az9gUCkcs1yJhBlNlki7e965ewZ7XjR0
"""

import os
import requests
import asyncio
import datetime
import pytz
from aiogram import Bot, Dispatcher, types
from aiogram.filters import Command

# 🔑 Токены из окружения
BOT_TOKEN = os.getenv("BOT_TOKEN")
YOUR_CHAT_ID = int(os.getenv("YOUR_CHAT_ID"))

# 🔍 Ключевые слова, регионы и статусы
KEYWORDS = ["кабель", "провод", "оптоволокно", "свет"]
REGIONS = ["270000000", "310000000", "350000000"]  # ЗКО, Атырау, Мангыстау
STATUSES = ["PUBLISHED", "COMPLETED", "CANCELED"]

# API Samruk-Kazyna
BASE_URL = "https://ows.goszakup.gov.kz/v3/tender"

# Отправленные тендеры
sent_tenders = set()

bot = Bot(token=BOT_TOKEN)
dp = Dispatcher()

# ⚡ Получение тендеров
def get_tenders(keyword, region, status):
    params = {
        "search_text": keyword,
        "customer_region": region,
        "purchase_status": status,
        "page": 1,
        "limit": 5
    }

    headers = {}
    API_KEY = os.getenv("API_KEY")  # 🔑 возьми из окружения (если он у тебя есть)
    if API_KEY:
        headers["Authorization"] = f"Bearer {API_KEY}"

    r = requests.get(BASE_URL, params=params, headers=headers)

    print("➡️ Запрос:", r.url)          # полный URL запроса
    print("🔢 Код ответа:", r.status_code)
    try:
        data = r.json()
        print("📩 Ответ:", data)
    except Exception as e:
        print("❌ Ошибка разбора JSON:", e)
        print("Текст ответа:", r.text)
        return []

    if r.status_code == 200:
        return data.get("items", [])
    return []


# 🚀 Отправка новых тендеров
async def send_new_tenders(chat_id):
    global sent_tenders
    for kw in KEYWORDS:
        for reg in REGIONS:
            for st in STATUSES:
                tenders = get_tenders(kw, reg, st)
                for t in tenders:
                    tid = t.get("id")
                    if tid not in sent_tenders:
                        sent_tenders.add(tid)
                        region_name = t.get("regionNameRu", "Неизвестно")
                        text = f"""
🔔 Новый тендер найден!
📄 {t.get('nameRu')}
🏢 {t.get('customerNameRu')}
🌍 Регион: {region_name}
📅 Дата публикации: {t.get('publishDate')}
📎 Ссылка: https://zakup.sk.kz/#/purchase/view/{tid}
"""
                        await bot.send_message(chat_id, text)

# 🕒 Проверка каждый час с 06:00 до 23:00 (Asia/Almaty)
async def scheduler(chat_id):
    tz = pytz.timezone("Asia/Almaty")
    while True:
        now = datetime.datetime.now(tz)
        if 6 <= now.hour < 23:   # Работает только с 6 утра до 23:00
            await send_new_tenders(chat_id)
        await asyncio.sleep(3600)  # проверка каждый час

# 🔘 /start
@dp.message(Command("start"))
async def start_cmd(message: types.Message):
    await message.answer("Привет 👋\nЯ бот для мониторинга закупок Samruk-Kazyna.\n"
                         "Проверяю каждый час с 06:00 до 23:00 (Asia/Almaty).\n"
                         "Используй /check для ручной проверки.")

# 🔘 /check
@dp.message(Command("check"))
async def check_cmd(message: types.Message):
    await send_new_tenders(message.chat.id)
    await message.reply("✅ Бот работает!")

# 🚀 Запуск
async def main():
    me = await bot.get_me()
    print(f"Бот запущен: @{me.username}")
    asyncio.create_task(scheduler(YOUR_CHAT_ID))
    await dp.start_polling(bot)

if __name__ == "__main__":
    asyncio.run(main())
